feat: Added Preloader
dvjsharma/Drawn2Shoe pull request #108
Opened 2024-07-05 11:21 UTC by AsmitaMishra24

## Description
Added Preloader.

Issue No.:
Fixes #106 

Screenshot:-
https://github.com/dvjsharma/Drawn2Shoe/assets/146121869/1853f739-b28b-43d6-8e81-64bc745b50e4

2024-07-06 13:39 UTC, dvjsharma commented on client/src/components/Preloader/Preloader.json
Is there any CDN which provides this `json` over links?

2024-07-06 13:39 UTC, dvjsharma commented on client/src/components/Preloader/Preloader.json
Is there any CDN which provides this `json` over links?

2024-07-06 13:40 UTC, dvjsharma commented on client/src/components/Preloader/Preloader.jsx
> +            <Lottie className="preloader-animation" animationData={preloaderAnimation} />
Please provide screenshots since this is a UI PR.

2024-07-06 13:40 UTC, dvjsharma requested changes
Some questions, PTAL.

2024-07-06 14:46 UTC, AsmitaMishra24 commented
@dvjsharma, I have added a preloader.json obtained from the lottiefiles website, but I can also design one using CSS. The design will be simple.

2024-07-06 14:49 UTC, AsmitaMishra24 commented
@dvjsharma, I will design it with CSS...in 2-3 days

2024-07-06 15:17 UTC, dvjsharma commented
The current design looks good to me. Just see if there are alternate on link delivery for the json file, else we can go with the current format.

2024-07-07 08:58 UTC, AsmitaMishra24 commented
The alternative methods for delivering the JSON file are quite similar to the current format, so the current format is good to go. Alternatively, we can create a link for the JSON file.

2024-07-07 09:27 UTC, dvjsharma commented
Yep, that’s what I’m concerned about. See if you can replace the JSON with a deliverable link, so we don’t have to manage the JSON file in code itself.

2024-07-07 09:55 UTC, AsmitaMishra24 commented
> Yep, that’s what I’m concerned about. See if you can replace the JSON with a deliverable link, so we don’t have to manage the JSON file in code itself.

Ok, I will let you know in 2 days.

2024-07-09 17:47 UTC, AsmitaMishra24 commented
@dvjsharma, I've searched this, and it appears that adding JSON files via links is only feasible in traditional html and js only. In React, this method isn't applicable. Most resources suggest directly adding the JSON file to the project.

For reference:-
When working with traditional HTML and JavaScript, it's possible to dynamically load JSON files using <script> tags and the src attribute. However, in React applications, we leverage modern JavaScript modules and utilize the import statement to include JSON files directly into our JavaScript code. This is due to React's modular structure and how assets are managed during the build process.

2024-07-09 17:50 UTC, AsmitaMishra24 commented
Could you upgrade the level. I received level 2 for the same work in other repos.

2024-07-09 18:35 UTC, dvjsharma commented
There are methods to inject scripts, but the current implementation appears satisfactory. I think level 1 is good enough for this feature request. We'll see if this requires an upgrade.
Thanks for your contribution.

2024-07-09 18:36 UTC, dvjsharma approved these changes
Changes looks good.

2024-07-09 18:37 UTC, merged