feat: automate greetings using github bot
dvjsharma/Drawn2Shoe pull request #41
Opened 2024-05-14 15:32 UTC by dakshsinghrathore

This PR fixes the issue #33  , kindly review it and merge. @dvjsharma 

You need to give `read and write permission` to the bot to make comments hence kindly go to the repo  `settings/actions/General`  and under  `Workflow Permissions`  grant  `Read and write` permissions and then `save`.

like this ⬇️

![image](https://github.com/hereisSwapnil/ExamTime/assets/115932772/e6f1f159-4d57-4030-af8e-90bcf7f3f4a0)

2024-05-14 18:35 UTC, dvjsharma requested changes
Minor changes needed

2024-05-14 18:37 UTC, dvjsharma requested changes
Minor changes needed

2024-05-14 18:37 UTC, dvjsharma commented on .github/workflows/greetings.yml
> +    branches: [main]
Replace with `master`

2024-05-14 18:37 UTC, dvjsharma commented on .github/workflows/greetings.yml
> +          footer: 'We will promptly review your changes and offer feedback. Keep up the excellent work! Kindly remember to check our [contributing guidelines](https://github.com/dvjsharma/Drawn2Shoe/
Grammatical errors, please check with AI models.

2024-05-17 19:32 UTC, dvjsharma commented
Any updates @dakshsinghrathore?

2024-05-31 03:59 UTC, dakshsinghrathore commented
@dvjsharma have made the changes kindly review

2024-05-31 14:15 UTC, dvjsharma commented
@dakshsinghrathore Can't see any. Please re-check

2024-06-07 19:22 UTC, dvjsharma commented
Closing since no response. Please re-open if necessary.

2024-06-07 19:22 UTC, closed without merging