Dark Mode added.
dvjsharma/Drawn2Shoe pull request #57
Opened 2024-05-17 14:08 UTC by SwanandD121

## Description
A Dark Mode feature has been added, which includes an interactive toggle button for user convenience.

### Changes

- All UI components have been updated with darker tones to reduce eye strain.
- The feature automatically detects the browser's theme and adjusts the website's theme accordingly upon loading.

## How to test
To test the Dark Mode functionality, click on the sun/moon icon located in the navbar. This will toggle between Dark Mode and Light Mode.

![image](https://github.com/dvjsharma/Drawn2Shoe/assets/117746995/2d6dba0e-6255-416c-a847-781975e03251)

Resolves #49

2024-05-17 19:15 UTC, dvjsharma requested changes
Major changes, please take a look.

2024-05-17 19:16 UTC, dvjsharma requested changes
Major changes, PTAL.

2024-05-17 19:16 UTC, dvjsharma commented on client/src/ThemeContext.jsx
We utilize Redux for state management instead of the context API. This would lead to 2 state management practices which is not recommended. Please look for a redux based alternative.

2024-05-18 03:48 UTC, SwanandD121 commented on client/src/ThemeContext.jsx
> We utilize Redux for state management instead of the context API. This would lead to 2 state management practices which is not recommended. Please look for a redux based alternative.

Alright, working on it.

2024-05-18 04:57 UTC, SwanandD121 commented
Changed the dark mode logic implementation using Redux Toolkit.
Resolved one conflict in Guide component.

Fixed #49

2024-05-18 05:08 UTC, dvjsharma commented
Please squash the commits into one so we can track all dark mode related changes together.

2024-05-18 05:26 UTC, SwanandD121 commented
> Please squash the commits into one so we can track all dark mode related changes together.

Done.

Fixed #49

2024-05-18 05:29 UTC, SwanandD121 commented
> Please squash the commits into one so we can track all dark mode related changes together.

Done.

Fixed #49

2024-05-18 17:54 UTC, dvjsharma approved these changes
Code Looks good.
@ShashankShekhar07 Please test with latest master and review

2024-05-18 17:55 UTC, dvjsharma commented
Good work @SwanandD121, Please rebase with master

2024-05-19 05:40 UTC, SwanandD121 commented
> Good work @SwanandD121, Please rebase with master

Tried rebasing, but everything is up to date. Working tree is clean.

2024-05-19 06:39 UTC, SwanandD121 commented
> Good work @SwanandD121, Please rebase with master

Done with rebasing. Resolved 1 conflict.
Fixed #49

2024-05-23 07:35 UTC, ShashankShekhar07 commented
Hey Well Done @SwanandD121. I think you forgot adding dark mode feature in retailer page. Also the theme button vanishes when the user is logged in. Please see through it.

2024-05-23 10:48 UTC, SwanandD121 commented
> Hey Well Done @SwanandD121. I think you forgot adding dark mode feature in retailer page. Also the theme button vanishes when the user is logged in. Please see through it.

Thanks. I'll check the things you mentioned and get back to you.

2024-05-31 14:25 UTC, dvjsharma commented
any updates @SwanandD121?

2024-05-31 15:12 UTC, SwanandD121 commented
> any updates @SwanandD121?

I'm having trouble connecting backend to frontend and running the entire app, I mailed you 3-4 days ago but I haven't heard from you.

2024-05-31 15:30 UTC, dvjsharma commented
Will do. 
CC @ShashankShekhar07

2024-06-03 13:12 UTC, closed without merging